### ISSUE TITLE
demo_OnACID_mesoscope - Calcium traces offset with neuron #

### ISSUE THREAD

**Issue by catubc** [simonsfoundation/CaImAn#102]
Hi

I'm trying to use traces output from demo_OnACID_mesoscope, but they seem to be offset as I scroll through the neuron #s.

https://github.com/catubc/yuste/blob/master/traces.png

Here's the bokeh file:
https://github.com/catubc/yuste/blob/master/alejandro.html

Thanks.

**Comment by epnev** [comment]
This is normal and due to the online processing mode. As the algorithm goes through the dataset it adds detects new neurons but the assumption is that the past data is no longer available so the activity is set to zero. Setting the variable epochs to number larger than set, will make the algorithm go through the data more times, and as such it will "smooth" their trajectories.
